---
title: "Auswertung Temperatur- und Feuchtigkeits-Daten 18.11.2025-09.12.2025"
author: "Robin Gummels, Humam Hikmat, Lenn Kruck"
format: 
  revealjs: 
    theme: dark
editor: visual
---

# Wir haben unsere Auswertung mit der Programmiersprache R gemacht

## Was ist R?
- Open-Source Programmiersprache speziell für Statistik und Datenanalyse
- Bringt tausende Pakete für Auswertung, Visualisierung und Reproduzierbarkeit mit
- Funktioniert interaktiv (Konsole/RStudio) und in Skripten für reproduzierbare Workflows
- Läuft auf allen gängigen Betriebssystemen und ist frei verfügbar

## Warum R?
- Saubere Trennung von Code, Daten und Ergebnis: Analysen bleiben nachvollziehbar
- Starke Visualisierung (z.B. `ggplot2`) für schnelle Diagramme unserer Messdaten
- Große Community und Dokumentation; Probleme sind meist schon gelöst
- Passt gut zu Quarto: Text, Code und Grafiken in einer präsentation kombinierbar

## Slide 2

When you click the **Render** button a document will be generated that includes:

-   Content authored with markdown
-   Output from executable code

## Slide 3 mit Code 1

When you click the **Render** button a presentation will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
#| echo: true
1 + 1
```